### ISSUE TITLE
2ch.hk - bug

### ISSUE THREAD

**Issue by perdolka** [dralletje/Windowed#10]
Deactivating Windowed mode (gray button) doesn't help on **2ch.hk** pages,
Temporary solution: turning off an addon on the about:addons page.
same on mirror - 2ch.pm

FF 60.9.0esr

**Comment by dralletje** [comment]
Thanks!

It's rather hard for me to find a video/fullscreen-able item on this website to test with, as I don't speak Russian very well 😁 
Could you link me to a video/element that you are expecting to fullscreen?

**Comment by perdolka** [comment]
Now, it just doesn't work, so I think the problem is on the site side.

> Could you link me to a video/element that you are expecting to fullscreen?

https://2ch.hk/tv/res/2531514.html#2541570

**Comment by dralletje** [comment]
Seems like this is because these videos are native `<video />` players, which I can't nicely wrap :(
