### ISSUE TITLE
Bug in videos, where "Enter fullscreen" dialogue does not disappear after new window has opened

### ISSUE THREAD

**Issue by ktkwon00** [dralletje/Windowed#11]
Hi, I was trying this extension with videos on panopto and I found that although the extension opens the fullscreen video in a new window, the dark overlay with the "Enter fullscreen" dialogue does not disappear.
![image](https://user-images.githubusercontent.com/14355090/66268628-d391b180-e871-11e9-837c-011c51029df6.png)

How to reproduce: access https://demo.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=30b8b6bb-f509-4417-889c-aa53016ce6af (or any link on this [list of videos](https://www.panopto.com/resources/video-recordings/)) and enter fullscreen, using the button that becomes visible in the top right hand corner of the video when your cursor moves over it.

Thanks!

**Comment by dralletje** [comment]
Couldn't reproduce now, but I did see the fullscreen element has a margin-top and margin-left in the style attribute, and I just can't overwrite that :(
