### ISSUE TITLE
Black frames for not responsive videos

### ISSUE THREAD

**Issue by miguel-olivero** [dralletje/Windowed#15]
Could there be a black frame to wrap the video for these cases on which the video is not covering the full size of the window when using "IN WINDOW" mode?

Some times the video fill up to the full width of height, the higher value but not both simultaneously.
In these cases, sometimes you can see the website in the foreground. It would be interesting to add black frames just to allow better video watching.

**Comment by dralletje** [comment]
I can't put a black layer "between" the video and the background, because the video is most of the time nested "inside" the background. I'd rather look at how to make the videos cover everything.. do you have a link to a website that doesn't fill up all the way?
