### ISSUE TITLE
bug(firefox): shortcut for Windowed mode

### ISSUE THREAD

**Issue by Kristinita** [dralletje/Windowed#16]
### 1. Summary

Shortcut for `Windowed` mode doesn't work in my Firefox.

#### 2.1. Reproducibility

I reproduce the problem in the newest version of stable portable Firefox without any another extensions and user settings.

#### 2.2. URLs

1. [**PeerTube**](https://video.ploud.fr/videos/watch/37d2ac34-a6b9-423f-a6df-937bff257405)
1. [**YouTube**](https://www.youtube.com/watch?v=bqrYgR36wwo)

#### 2.3. Steps to reproduce

I open PeerTube or YouTube URL → `f`:

![Fullscreen mode](https://i.imgur.com/3N2vPEH.png)

→ `w`.

#### 3.1. Firefox

No effect after `w` button. I need manually click to `Windowed` word.

#### 3.2. Chromium

YouTube/PeerTube URL in windowed mode.

It's good, but I need to disable some another extensions.

#### 3.3. Expected

[**Customizable hotkeys**](https://www.ghacks.net/2019/01/16/manage-firefox-add-ons-keyboard-shortcuts-on-aboutaddons/).

`f` and `w` keys may be already used by another extensions as [**Surfingkeys**](https://github.com/brookhong/Surfingkeys). It would be nice, if would be possible set custom hotkeys for Windowed.

### 4. Environment

1. Windows 10.0.18363 Pro N for Workstations 64-bit EN
1. Browsers:

    1. Firefox 76.0.1 (64-bit)
    1. Chromium 81.0.4044.129 (Official Build) (64-bit)

1. Windowed

    1. Firefox — 23
    1. Chromium — 22

Thanks.

**Comment by dralletje** [comment]
This should be fixed in the newest version for firefox (version 27)
