### ISSUE TITLE
Request: Disable for URL

### ISSUE THREAD

**Issue by mnilsson76** [dralletje/Windowed#17]
Hi,

It would be great if it was possible to exclude certain sites or URL wildcards. For instance, I run Octoprint for my 3D printer, and if I press the maximize icon in that web interface (which basically brings up the most useful information and the webcam picture in a white on black design across the whole browser window) the interface first does what I ask of it, but after it has been maximized your extension pops up the "3 alternatives" selection box. Now I have no use for that selection box.

![Octoprint web interface](https://user-images.githubusercontent.com/43128623/85928564-2bfc5980-b8ae-11ea-9d52-e2f7f1cbb47d.png)
![Octoprint web interface - maximized](https://user-images.githubusercontent.com/43128623/85928573-47fffb00-b8ae-11ea-8118-2e857a2a8abb.png)

**Comment by dralletje** [comment]
Hey! Should look at these issues more often 🙃 
You should be able to press the windowed icon in your url bar to disable windowed for a certain domain.
The icon will dim when it is disabled.

Maybe I should also add a disable option to the popup menu... 🤔
