### ISSUE TITLE
Hide window top bar?

### ISSUE THREAD

**Issue by sinedied** [dralletje/Windowed#18]
I love this extension!
Do you think it would be possible to have an option to hide the window top bar with the controls, and reveal it on hover or with a shortcut?
I use this extension for presentations, and it would be helpful to have that option :)
Thanks for your work on this extension.

**Comment by dralletje** [comment]
I'd love to, it's not possible with the way my extension works however.
I re-use the existing running chrome tab, which is only allowed to be popped in a "popup", which has the url bar.
Other windowed apps use a new special "App" window, which isn't allowed to share any cookies or data with the main chrome instance.

**Popup (Windowed)**
- **\+** Continue on the page without any reload
- **\+** Can access logged in account and other parts of chrome profile
- **\-** Has a frame (top bar)
- **\-** Can't float on top automatically (possible with a different app? Not sure)

**App window**
- **\-** Reloads page whenever you go into windowed/floating mode
- **\-** Can't access chrome data, so need to login first time going into windowed/floating mode
- **\+** Can be frameless (beautiful!!!)
- **\+** Can float on top of other windows automatically!! (Also very nice)

Whenever it is possible to combine all pros, I will hahaha, I do love frameless looking windows as much as the next guy 😁
