### ISSUE TITLE
[Feature request] Add keyboard shortcuts

### ISSUE THREAD

**Issue by aacebedo** [dralletje/Windowed#20]
Hi 

I've just installed your extension and it is perfect to use it with i3wm !
Can you add the ability to bind keyboard shortcut to the different display modes ?

It would enable me to easily pop-out the video without using the mouse.

**Comment by alecperkey** [comment]
used to work with w-windowed i-inWindow f-fullScreen

but lately is not for any sites for me. also the YT keyboard shortcuts conflict with those (w, i, f)

**Comment by dralletje** [comment]
A fix for this is now released on Firefox, and it's in review for Chrome!
I'll comment again when the Chrome version is also live so you can let me know if it also works for you 😁
