### ISSUE TITLE
Disable Picture-in-Picture

### ISSUE THREAD

**Issue by ApexAU** [dralletje/Windowed#22]
Hi, thanks for this extension, it's extremely useful and I appreciate the time you took to develop it.  I have a very minor query: is it possible to remove or disable the picture-in-picture option on Youtube.com and/or other websites?  After using this extension for quite a while, I have developed muscle memory to click on the last option under "maximise" to select "'Fullscreen" video.  As "PiP" has recently replaced "Fullscreen's" position at the bottom of the menu, I am constantly clicking on "PiP" when I meant to select "Fullscreen".  

Is it possible for you to add an option to disable PiP, or for me to roll-back to an earlier version of the extension without PiP?  I know this is a fairly trivial request but I would appreciate a solution if possible.  Thanks again!

**Comment by dralletje** [comment]
Hahahaha, amazing 😂 
I've just pushed a new commit that moves PiP to the top position of the menu, and will put that on all the stores today (Chrome takes some days to review)

**Comment by ApexAU** [comment]
It's live for me now!  Thank you so much for indulging my petty complaint and pushing a fix within a day.  That's incredible support for a Chrome extension.  I truly hope you have an excellent 2021!
