### ISSUE TITLE
[Feature Request] Have a dedicated button instead of reusing the fullscreen button

### ISSUE THREAD

**Issue by tmxkn1** [dralletje/Windowed#26]
As the title suggested, can we have an option to use a dedicated button? More than often when I click the full-screen button, I'd like to go straight to full screen.

**Comment by dralletje** [comment]
I can't automatically add a button next to fullscreen, as I can't

**Comment by EthanGe77** [comment]
Hey, @dralletje I like the idea of being able to `shift` click any fullscreen button and show the popup. or allow `shift` click to be full screen while not holding it will trigger that window

**Comment by dralletje** [comment]
>  I also like that your extension does not reload the page.
This is the main reason I made it :D
