### ISSUE TITLE
Multiple PiP Windows

### ISSUE THREAD

**Issue by RCPMAD** [dralletje/Windowed#28]
Hello,

Would it be possible to have multiple PiP windows? At the moment only one at a time works where opening a new one closes the old one. I stream from multiple sources at the same time and would like to be able to use PiP on all of them at the same time.

Mad

**Comment by dralletje** [comment]
No sorry, that's not possible :(
PiP is not something I control, contrary to Windowed mode, so it's all up to Chrome what to do.
Browsers are slow to implement nice PiP 🤷‍♀️
