### ISSUE TITLE
Disabling

### ISSUE THREAD

**Issue by drewex** [dralletje/Windowed#3]
Can you add enable disable option for this, clicking the icon would change the icon with / on it or some other visual and keeps it state.

**Comment by dralletje** [comment]
I made an update that includes a small popup when you click fullscreen now:
<img width="200" alt="screen shot 2018-10-02 at 5 34 19 am" src="https://user-images.githubusercontent.com/767261/46317261-0d97fa00-c605-11e8-98b7-aa3b7b5cdba4.png">

If you have time, you could help me out by testing it before I release it to everyone
https://chrome.google.com/webstore/detail/windowed-floating-youtube/nealbpdgoeelmaoegccbjojpiefpmjld

I'll add the chrome button feature as well, just in case the popup glitches or doesn't show up in sites where it doesn't work.

**Comment by dralletje** [comment]
Actually, added the button toggle now. Let me know if you can/have tested it out (You can download it with the link I provided above). Make sure you disable the old version when downloading the new one :)

**Comment by drewex** [comment]
I just had a change to test it for once seems to work fine.  only concern I have your icon is black on the toolbar. Browser allows themes and black themes makes the icon not visible at all. Maybe bordering it might be good.

**Comment by dralletje** [comment]
I bordered it with a white border after some tinkering to make sure it looks good on multiple themes, thanks :)
I now published the version to the store!
