### ISSUE TITLE
Not showing pop up options

### ISSUE THREAD

**Issue by chibi243** [dralletje/Windowed#30]
This app is showed geyed out on the 9anime.ru site, it had worked before on firefox.  It works on animekisa, anime8 [things like that]
![Screen Shot 2021-04-29 at 9 36 28 AM](https://user-images.githubusercontent.com/59479322/116569545-1b9e7c00-a8cf-11eb-9dd0-c92c12860578.png) [9anime] [please fix this]

![Screen Shot 2021-04-29 at 9 42 18 AM](https://user-images.githubusercontent.com/59479322/116569660-3a9d0e00-a8cf-11eb-86fd-6847f7b9d35c.png) [AnimeKisa]

Thank you for your time and a fantastic app! ^-^

**Comment by dralletje** [comment]
From what I tried it works again on 9anime, so closing this.
Feel free to reopen with more info if it doesn't work for you still.
