### ISSUE TITLE
documentation: is this supposed to work with fullscreen for any site or just video players?

### ISSUE THREAD

**Issue by DavidGretzschel** [dralletje/Windowed#39]
In Chrome, when I press F11 or the fullscreen-button (see picture), it will use the normal (and unnecessarily space-hogging) full-screen.
![image](https://user-images.githubusercontent.com/23729465/146130176-61e261bd-6dc2-4f60-a311-56858c1fc3f4.png)
![image](https://user-images.githubusercontent.com/23729465/146131316-02770b56-3344-446d-ba5d-546c33034f3b.png)

I was hoping for a OneNote-style windowed-fullscreen like this, though:
![image](https://user-images.githubusercontent.com/23729465/146130533-b048939a-766f-4dd2-9bf0-1baebccbf9b9.png)

I understand that this might not be possible. 
[or perhaps this is not possible in Chrome, but possibly Firefox? I wouldn't know, I'm using Chrome]
But I couldn't figure this out from the documentation here:
https://chrome.google.com/webstore/detail/windowed-floating-youtube/gibipneadnbflmkebnmcbgjdkngkbklb

The description of "Changes fullscreen buttons to go into a popup. Works for every website that uses fullscreen, including Youtube, Vimeo, Netflix" did get my hopes up. 
The browser itself does have a full-screen button.
I do appreciate having this for YouTube, of course.

But a true windowed FullScreen-mode would be something much greater.
And if that's not in the cards, it would be better, to state that clearly.

**Comment by dralletje** [comment]
I can't change the browser fullscreen button, sadly, but I do get the confusion.
There might be a nice UI for adding buttons to pop out to a windowed popup somewhere in the windowed menu?
<img width="242" alt="Windowed Menu" src="https://user-images.githubusercontent.com/767261/153733769-f056b5ca-bce4-477e-8b8c-d13cf54bc042.png">

But for now you will have to do with manually executing `document.body.requestFullscreen()` in the javascript console :/ 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/767261/153733782-4591ad9e-f5e1-4f58-8efb-c060799bf0cd.png">
