### ISSUE TITLE
I think the fullscreen icon should be left alone

### ISSUE THREAD

**Issue by alivefromupstairs** [dralletje/Windowed#4]
your extension out of all the extensions to play YT videos windowed is the best (works with other extensions, isn't embedded style, . but I think it would be better to have another standalone icon. and maybe a standalone hotkey too. if I double click for fullscreen I have to press again. if I press "f" I have to reach for my mouse or 3 other keystrokes. I think an independent experience (as one doesn't want to play every video in windowed mode, while some would play the majority of videos in fullscreen) would be a make a better UX.
Thanks for the good extension.

**Comment by dralletje** [comment]
Although I have no way to reliably add an icon to other websites, and it's a feature that it does work with any fullscreen, I do see how youtube might be so popular that it might be warrant an exception. I'll see how much work it is to implement the extra button, and then decide whether it is worth it :)
Thanks a lot for the suggestion either way! I'll keep you updated!

**Comment by dralletje** [comment]
After seeing how much youtube subtly updated its full screen behavior, I'm afraid to add a youtube specific (breakable) implementation. Closing this until some magic solution shows up ;)
