### ISSUE TITLE
[Feature request] Support for TradingView

### ISSUE THREAD

**Issue by tobia** [dralletje/Windowed#41]
I tried using this extension to keep a floating TradingView chart on top of my screen at all times, but the fullscreen button (top toolbar, third from the right) just goes into fullscreen, without being intercepted by this extension.

**Comment by dralletje** [comment]
Do you have an easily reproducible example for me?

**Comment by tobia** [comment]
Sure. You can just open the default chart at https://www.tradingview.com/chart/ and use the fullscreen icon:

![Screenshot 2022-02-11 at 00-19-06 Live stock, index, futures, Forex and Bitcoin charts on TradingView](https://user-images.githubusercontent.com/48756/153513492-45424cbb-4d3f-47c2-b514-68c8e3bbdd5d.png)

**Comment by dralletje** [comment]
Thanks!

Will look more into it, but just to confirm: you are getting the popup?
For me the page does jump into a fullscreen-ish mode and then shows me the popup, but selecting windowed will just force it into fullscreen anyway:

![image](https://user-images.githubusercontent.com/767261/153672793-3f3f9fc0-1d57-4508-9c79-99f7aa8e1359.png)

**Comment by tobia** [comment]
I get no popup, it just goes into fullscreen. I also tried changing the default mode for the website, using the toolbar icon, but no matter what I choose it always goes into fullscreen, ignoring the extension.

But I noticed the following errors in the console:

![windowed-error](https://user-images.githubusercontent.com/48756/153674993-a24767a9-b8e5-446e-b6d8-81edd216b933.png)

I'm using Firefox 96.0 (64-bit) for Ubuntu, but yesterday I was using the latest Firefox on Windows. I also tried creating a new Firefox profile, without any extensions or custom settings except for Windowed, and I get the same behavior and the same error message.

I'm no expert at Content Security Policy, but it might be that TradingView (and others) are enabling some optional high-security settings that block unsigned scripts, like Windowed's injected one, from running.

**Comment by dralletje** [comment]
Ah, you're on firefox! I was expecting Chrome 😁 I'll test on firefox!

**Comment by dralletje** [comment]
Okay, got it! Can you upgrade windowed and try it out?

**Comment by tobia** [comment]
It works perfectly! Thank you! 🎉
