### ISSUE TITLE
[Request] Steam Support

### ISSUE THREAD

**Issue by livejamie** [dralletje/Windowed#43]
Brilliant extension, thank you!

Would love support for Steam videos.

Example: https://store.steampowered.com/app/1245620/ELDEN_RING/

**Comment by dralletje** [comment]
I'm very sorry, but "it works on my machine" 🥲

So I'll need some more info.. What browser are you using? What is happening instead of what you expect is happening? Maybe a screenrecording!

Thanks 😁

**Comment by livejamie** [comment]
Seems to be a conflict between  this extension and https://github.com/IsThereAnyDeal/AugmentedSteam

**Comment by dralletje** [comment]
Nice catch, thanks.
Can't fix it, but want to make a centralised list.
