### ISSUE TITLE
Feature request: Option to disable double-click activation

### ISSUE THREAD

**Issue by mattalexx** [dralletje/Windowed#52]
I'm trying to skip a YouTube video forward by double-clicking the right half of the video, but that action only opens the Windowed menu. I wish I could disable that.

- Windowed Version 28
- Chromium Version 105.0.5195.125 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

**Comment by dralletje** [comment]
It only opens when the webpage wants to go into fullscreen, so I think the double-clicking the right half of the video would normally trigger fullscreen. Try double-clicking with the extension disabled and let me know.
