### ISSUE TITLE
[Site Request] Streamable

### ISSUE THREAD

**Issue by livejamie** [dralletje/Windowed#58]
It would be nice if it worked for videos from Streamable, one of the most embedded video sites, especially on Reddit.

Example: https://www.reddit.com/r/nba/comments/11fn87c/highlight_kd_gets_a_block_then_immediately_hits_a/

**Comment by dralletje** [comment]
Hey! It works for me on chrome and firefox, both on reddit (though on reddit the video it stays tiny while fullscreen).
Could you describe what problem you are having a liiiiitle bit better? :D

**Comment by livejamie** [comment]
Ah it staying tiny is the issue I was running into :)
