### ISSUE TITLE
Not working with embedded ustream videos

### ISSUE THREAD

**Issue by apparle** [dralletje/Windowed#6]
It looks like the extension is unable to detect the "Full Screen" button on embedded ustream videos and does not show the small menu to select "windowed". Here's a example link: https://pste.eu/p/HqbA.html

This is on Google Chrome v74.0.3729.131 (64-bit) on Windows 10 with extension version 20.

PS: This is an great extension! Thanks for developing and maintaining it.

**Comment by apparle** [comment]
Since the link mentioned has disappeared, adding example html code to reproduce the problem. To reproduce the problem you can create this html in a local file or online html renderer.

```
<html>
<body>
<h1>Foo Heading</h1>
<p>Foo paragraph.</p>
<iframe width="480" height="270" src="https://ustream.tv/embed/recorded/120712252" scrolling="no" allowfullscreen webkitallowfullscreen frameborder="0" style="border: 0 none transparent;"></iframe>
<p>Bar paragraph.</p>
</body>
</html>
```

**Comment by dralletje** [comment]
Hey, just saw this!
What's strange is that when I load this extension manually from this repository (which is the same code as the one currently in the chrome webstore), the snippet **does** work 🤔 

I'll do some more experiments on this in the weekend :)

**Comment by dralletje** [comment]
I've released a new version, and it seems to work! I tested on firefox, will test on chrome once it has been approved.

**Comment by apparle** [comment]
It was been working for me in Chrome as well. Thanks for the fix.
