### ISSUE TITLE
remove window border

### ISSUE THREAD

**Issue by coookie-cR** [dralletje/Windowed#64]
Hello, 

Happy Sunday, apologies in advance if this has been answered or if I may be asking in the wrong section. I have been using this extension for quite some time and I love it. I am just wondering if there is a way to remove the border when applying the 'windowed' option. For reference:

![Capture](https://github.com/dralletje/Windowed/assets/149968811/b177bae4-5eef-483c-b174-59b892d90e8b)

**Comment by dralletje** [comment]
No :(

Only using the PIP method, but that only allows one window...
I would love to have a way to remove the title bar too
