### ISSUE TITLE
Option to keep ratio when resizing in Windowed Mode

### ISSUE THREAD

**Issue by ClaudioPiccinni** [dralletje/Windowed#7]
I think it would be awesome if it had an option, maybe CTRL or SHIFT hotkey, when resizing a window in Windowed Mode so it keeps the video proportion/ratio.

**Comment by dralletje** [comment]
I've been experimenting with this, but can't get it to work, sorry :(

**Comment by ClaudioPiccinni** [comment]
Thanks for giving it a try! It's a super awesome extension I use daily ;)
