### ISSUE TITLE
Feature-request: Hide as much as possible from the top-bar

### ISSUE THREAD

**Issue by Wolfskii** [dralletje/Windowed#71]
It would be nice to hide/temporarily toggle off the bookmarks bar and (if even possible) to hide the address bar and tabs when clicking the action button, e.g. when going into In-window mode, to make it seem more like a traditional "Fullscreen" in that window.

This is how it looks currently, which is already amazing for us Ultrawide-users (thank you):
![image](https://github.com/user-attachments/assets/47a502d7-88d4-40b3-8531-e778d3770cce)

**Comment by dralletje** [comment]
I know right! But it isn't possible, sadly.
The extension is very much bound by the limits set by Chrome.
