### ISSUE TITLE
Focus on Windowed's contextual menu when open

### ISSUE THREAD

**Issue by Ezep** [dralletje/Windowed#8]
Like me you probably use keyboard shortcuts a lot, and you love them.

When contextual menu opens up the focus event is still on the video, so you can't select fullscreen mode with arrow keys, making it mandatory to use mouse.

It would be great if you can press <kbd>F</kbd> to open contextual menu and then arrow keys to select the desired option.

Great extension! thanks for making it open source. It works amazing with tiling wm

**Comment by dralletje** [comment]
Great idea actually.

I want to make the extension as much "browser internal"-like as I could, so this should definitely be in!

What is in the new release:
- When the menu opens, it now has focus, and you can select the options with <kbd>TAB</kbd>, and then active that with either <kbd>Enter</kbd> or <kbd>Spacebar</kbd>
- You can also select the options with their own shortcuts, active when the menu is open (<kbd>w</kbd> for windowed mode, <kbd>i</kbd> for in-window mode and <kbd>f</kbd> for normal fullscreen

What is not included:
- Using the arrow keys to navigate. It's strange though, I kinda feel like this should be there as all browser dropdowns and menus do this, but it is not at all something the browser normally provides using web apis. For this reason, I leave it out now, until I find enough time or pressure to add it 😁 

I've released this version, firefox is already out. Just waiting for the Chrome team to verify it as well :)

**Comment by Ezep** [comment]
This is working perfect in Chrome, GNU/Linux (Ubuntu). Thanks for the feature, you are awesome!
