### ISSUE TITLE
Facebook bug

### ISSUE THREAD

**Issue by perdolka** [dralletje/Windowed#9]
Ring-button and Like popup doesn't work when addon is enabled.
![зображення](https://user-images.githubusercontent.com/24720263/65022976-9dc86f80-d93a-11e9-9093-10f7033699e2.png)
![зображення](https://user-images.githubusercontent.com/24720263/65023121-dff1b100-d93a-11e9-860c-5693478f74c0.png)
Deactivating Windowed mode (gray button) doesn't help on FB pages, 
Temporary solution: turning off an addon on the about:addons page.

FF 60.9.0esr

**Comment by dralletje** [comment]
Thanks for letting me know :)

I just released a new version for Firefox with this fix included!

For whoever is interested, a8c161e006f2ac93aae6279a528df328c6bdd8ad is the commit that fixed it :)
